phrase:
  project_id: d2d1deeecdfa41f343cf012bb225b24d
  push:
    sources:
    - file: en.json
      params:
        file_format: simple_json
        locale_id: en
        update_translations: true 
  pull:
    targets:
    - file: de.json
      params:
        file_format: simple_json
        locale_id: de 
        include_empty_translations: true 
    - file: ar.json
      params:
        file_format: simple_json
        locale_id: ar 
#        include_empty_translations: true 
